### ISSUE TITLE
接口路径不能重复

### ISSUE THREAD

**Issue by sglmsn** [fjc0k/YApi-X#16]
对于某些项目
比如我这个, 他的设定是接口路径唯一, 然后根据请求参数来判断走哪个接口的.
我现在想新增接口, 但是提示我已经存在相同路径接口且找不到地方可以修改这个限制...

**Comment by fjc0k** [comment]
因为 YApi 的 mock 地址是项目级别的，且不是根据接口 id 生成的，而是根据接口路径生成的，因此，如果路径相同，那 mock 地址就会冲突。

暂时建议你在接口路径后面加上无关的查询字符串以唯一化路径，比如: `/hello?_1`、`/hello?_2`
