### ISSUE TITLE
docker-compose起容器的时区问题

### ISSUE THREAD

**Issue by StaceyZhou2017** [fjc0k/YApi-X#18]
compose起镜像的时区能修改为宿主机器的时区吗？
自动化测试设置的时间与容器时间相同，与宿主机不同，导致执行时间需要人工加减计算

**Comment by fjc0k** [comment]
这个你应该去网上搜 如何将docker的时区设置为宿主机时区

**Comment by StaceyZhou2017** [comment]
嗯嗯，改过了，只是觉得每次搭建要设置一次呢



发自我的小米手机
在 Jay Fong <notifications@github.com>，2020年5月24日 下午9:02写道：

这个你应该去网上搜 如何将docker的时区设置为宿主机时区
