### ISSUE TITLE
请问docker一键部署都还需要单独起MongoDB服务吗

### ISSUE THREAD

**Issue by Zohar727** [fjc0k/YApi-X#20]
现在进去提示以下信息：
0: "启动引导服务..."
1: "写入配置..."
2: "等待 MongoDB 服务可用..."

**Comment by fjc0k** [comment]
纯粹的 docker 镜像就一个 yapi 啊，至于数据库，你必须手动提供。当然你可以使用 play 版，它自带数据库，具体看首页文档。

**Comment by fjc0k** [comment]
哦哦哦，这是 yapi-x 呀，如果是 docker-YApi，它提供了 play 版，自带数据库。YApi-X 没有 play 版。

**Comment by Zohar727** [comment]
> 纯粹的 docker 镜像就一个 yapi 啊，至于数据库，你必须手动提供。当然你可以使用 play 版，它自带数据库，具体看首页文档。

刚接触docker， 懂了谢谢哈

**Comment by asher-1995** [comment]
手动提供数据库，那么你的compose里为什么还要启动一个mongo服务
