### ISSUE TITLE
测试集合中，是否支持文件上传功能

### ISSUE THREAD

**Issue by ljzforever** [fjc0k/YApi-X#23]
在官方的版本，对于文件上传功能，文件上传接口选择了文件，再切换到该接口运行或者运行测试集合时候，文件就不存在了。请问这个版本是否支持测试集合中的文件上传吗？

**Comment by fjc0k** [comment]
对测试不太敏感，建议自行测试。

**Comment by ljzforever** [comment]
> 
> 
> 对测试不太敏感，建议自行测试。

好的。谢谢。
