### ISSUE TITLE
科学计数法

### ISSUE THREAD

**Issue by eyotang** [fjc0k/YApi-X#29]
1、在返回的响应中，返回数据正确。
{"code":0,"data":{"name":"WorldRoleListResponse","data":{"roleList":[{"playerId":108087106890940705}]}},"msg":"发送请求成功"}

2、通过获取响应包体中数据，填充到下一个请求中。发出的请求，显示为：108087106890940700，wireshark抓包也显示如此。
{{ $.40534.body.data.data.roleList[0].playerId }}

第一个请求的响应：
![image](https://user-images.githubusercontent.com/2398680/118765773-20db5f00-b8ae-11eb-97be-5954f0af7c52.png)

第二个请求：
![image](https://user-images.githubusercontent.com/2398680/118765839-351f5c00-b8ae-11eb-8fd8-cdaa6485f259.png)

第二个请求显示：
![image](https://user-images.githubusercontent.com/2398680/118767235-115d1580-b8b0-11eb-88e5-869415a9590f.png)

**Comment by fjc0k** [comment]
建议这种 id 以字符串传输。

**Comment by eyotang** [comment]
就是非字符串，就做不到呗？什么原因呢？给点解释？

**Comment by fjc0k** [comment]
自行谷歌  js 精度问题
